import Student from "./student.js";

const studentInstance1 = new Student("Alina", "Popok", 1990);
studentInstance1.present();
studentInstance1.present();
studentInstance1.present();
studentInstance1.absent();
studentInstance1.present();
studentInstance1.present();
studentInstance1.present();
studentInstance1.absent();
studentInstance1.present();
studentInstance1.present();
studentInstance1.present();
studentInstance1.absent();
studentInstance1.addMark(100);
studentInstance1.addMark(100);
console.log(studentInstance1.summary());
console.log(studentInstance1);
console.log(studentInstance1.getAge());

const studentInstance2 = new Student("Zefirchik", "Cat", 2017);
studentInstance2.present();
studentInstance2.present();
studentInstance2.present();
studentInstance2.present();
studentInstance2.present();
studentInstance2.present();
studentInstance2.present();
studentInstance2.present();
studentInstance2.present();
studentInstance2.present();
studentInstance2.present();
studentInstance2.present();
studentInstance2.present();
studentInstance2.present();
studentInstance2.present();
studentInstance2.present();
studentInstance2.present();
studentInstance2.present();
studentInstance2.present();
studentInstance2.present();
studentInstance2.present();
studentInstance2.present();
studentInstance2.present();
studentInstance2.present();
studentInstance2.present();
studentInstance2.addMark(100);
studentInstance2.addMark(100);
studentInstance2.addMark(100);
studentInstance2.addMark(100);
console.log(studentInstance2);
console.log(studentInstance2.getAge());
console.log(studentInstance2.summary());
